apiVersion: v1
kind: Service
metadata:
  name: geonetwork
  labels:
    name: geonetwork
spec:
  ports:
    - nodePort: 30010
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort