apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    name: webapp   
spec:
  containers:
  - image: terrama2/terrama2-webapp:4.0.11
    name: webapp
    ports:
    - containerPort: 36000
    resources: {}
    volumeMounts:
    - mountPath: /data
      name: repositorie-data
    - mountPath: /shared-data
      name: repositorie-data
    - mountPath: /root/.pgpass
      name: repositorie-data
  restartPolicy: Always
  volumes:
    - name: repositorie-data
      persistentVolumeClaim:
        claimName: repositorie-data-claim
status: {}
