apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: geonetwork
  name: geonetwork
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:  
      labels:
        service: geonetwork
      namespace: repositorie
    spec:
      containers:
      - env:
        - name: DATA_DIR
          value: /var/lib/geonetwork_data
        - name: POSTGRES_DB_HOST
          value: db4geonetwork
        - name: POSTGRES_DB_PASSWORD
          value: geonetwork
        - name: POSTGRES_DB_USERNAME
          value: geonetwork
        image: geonetwork:postgres
        name: core4geonetwork
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/geonetwork_data
          name: repositorie-data
      restartPolicy: Always
      volumes:
        - name: repositorie-data
          persistentVolumeClaim:
            claimName: repositorie-data-claim
status: {}