apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: geoserver
  name: geoserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: repositorie
      creationTimestamp: null
      labels:
        service: geoserver
    spec:
      containers:
      - env:
        - name: GEOSERVER_DATA_DIR
          value: geonetwork
        - name: GEOWEBCACHE_CACHE_DIR
          value: geonetwork
        image: kartoza/geoserver:2.13.0
        name: geoserver4geonetwork
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /opt/geoserver/data_dir
          name: repositorie-data
      restartPolicy: Always
      volumes:
        - name: repositorie-data
          persistentVolumeClaim:
            claimName: repositorie-data-claim
status: {}