apiVersion: v1
kind: Pod
metadata:
      labels:
        app: RDR_NAME
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: RDR_NAME_nginx
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  hostNetwork: true
  dnsPolicy: Default
  args: ["$(RDR_NAME)"]
