apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: RDR_NAME
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123
args: ["$(RDR_NAME)"]