apiVersion: apps/v1
kind: Deployment
metadata:
  name: labtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: LabTEST
  template:
    metadata:
      labels:
        app: LabTEST
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
