apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
  namespace: repositorie
spec:
  selector:
    io.kompose.service: geonetwork
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  type: NodePort
