apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${RDR_NAME}_postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${RDR_NAME}
  template:
    metadata:
      labels:
        app: ${RDR_NAME}_postgres
    spec:
      containers:
        - name: ${RDR_NAME}_postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
