apiVersion: v1
kind: PersistentVolume
metadata:
  name: repositorie-data
  namespace: repositorie
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"