apiVersion: v1
kind: Service
metadata:
  name: ssh
  namespace: default
spec:
  type: LoadBalancer
  externalIPs:
    - 10.0.0.10
  loadBalancerIP: 104.199.75.69
  selector:
    app: ssh
  ports:
    # the port that this service should serve on
  - port: 22
    protocol: TCP
    targetPort: 22
