# This is the backend service
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-lb
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: labtest
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  
  loadBalancerIP: 104.154.109.191
  ports:

  - port: 80
    name: nginx
    targetPort: 80

  - port: 5432
    name: postgres
    targetPort: 5432

  - port: 8080
    name: eonetwork
    targetPort: 8080

  - port: 8081
    name: geoserver
    targetPort: 8081

  selector:
    # Selects nginx-ingress-controller pods
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: labtest