apiVersion: v1
kind: Service
metadata:
  name: owncloud
  labels:
    name: owncloud
spec:
  ports:
    - nodePort: 30030
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    name: owncloud
  type: NodePort
