version: "3.1"

services:

  geonetwork:
    image: geonetwork:postgres
    restart: unless-stopped
    container_name: core4geonetwork
    ports:
      - "8181:8080"
    environment:
      DATA_DIR: /var/lib/geonetwork_data
      POSTGRES_DB_HOST: db4geonetwork
      POSTGRES_DB_USERNAME: geonetwork
      POSTGRES_DB_PASSWORD: geonetwork
    depends_on:
      - postgres
    volumes:
      - geonetwork:/var/lib/geonetwork_data
    networks:
      -  net

  postgres:
    image: mdillon/postgis
    restart: unless-stopped
    container_name: db4geonetwork
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: geonetwork
      POSTGRES_USER: geonetwork
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      -  net

  geoserver:
    image: kartoza/geoserver:2.13.0
    container_name: geoserver4geonetwork
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8082:8080"
    environment:
      GEOSERVER_DATA_DIR: geonetwork
      GEOWEBCACHE_CACHE_DIR: geonetwork
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
    networks:
      -  net

networks:
  net: 
    external: 
      name: net
      
volumes:
  geonetwork:
  geoserver-data:
  postgres: